"""MCP tool schemas: analysis & solving primitives (decompile, CFG, crypto, symexec, patch, pcap, EVM, WASM)."""
from __future__ import annotations

from mcp.types import Tool


def tools() -> list[Tool]:
    return [
        Tool(name="rust_decompile",
             description="Decompile a Rust binary via Oxidizer (angr) — recovers per-function pseudocode for a Rust target (heavy monomorphised generics / core::/alloc:: noise that trips generic decompilers). Detects Rust by panic-handler signature; pass force=true to run on a stripped binary that doesn't fingerprint as Rust. Returns the decompiled functions (optionally only specific addresses). Needs angr (pip install angr).",
             inputSchema={"type": "object", "properties": {
                 "path": {"type": "string", "description": "Path to the Rust binary (PE/ELF/Mach-O)."},
                 "limit": {"type": "integer", "default": 20, "description": "Max functions to decompile."},
                 "addresses": {"type": "array", "items": {"type": "string"}, "description": "Specific 0x... addresses to decompile (overrides limit)."},
                 "force": {"type": "boolean", "default": False, "description": "Run even if the binary doesn't look like Rust."},
             }, "required": ["path"]}),
        Tool(name="vmp_devirt",
             description="Devirtualise a VMProtect / Themida-protected function via Mergen — lifts the VM handler chain to LLVM IR and writes a cleaned artefact you can re-decompile through Ghidra/r2, for a routine hidden behind a VMProtect/Themida dispatcher. Supply the binary and `start` = the VM-entry address (from a prior Ghidra/r2 pass, where control jumps into the obfuscated dispatcher). Needs the `mergen` binary (github.com/NaC-L/Mergen on PATH or CHIMERA_MERGEN_BIN).",
             inputSchema={"type": "object", "properties": {
                 "path": {"type": "string", "description": "The protected binary (PE for VMP; PE/ELF for Themida)."},
                 "start": {"type": "string", "description": "VM-entry address, e.g. 0x140001000 (required)."},
                 "out_dir": {"type": "string", "description": "Output dir for the lifted LLVM IR / cleaned binary (default: <name>_mergen)."},
                 "timeout": {"type": "integer", "default": 600, "description": "Subprocess timeout (seconds)."},
                 "mergen_bin": {"type": "string", "description": "Path to the mergen binary (default: PATH / CHIMERA_MERGEN_BIN)."},
             }, "required": ["path", "start"]}),
        Tool(name="find_dispatch_tables",
             description="Scan a PE for arrays of code pointers (a state-handler dispatch table or jump table) and validate each entry against the real function starts from the .pdata table — so it works even when a disassembler's call-graph walk is ILT-defeated. The largest table's length is typically the state/handler count of a generated state machine or VM interpreter. Returns candidate tables (section, base VA, entry count, pointer size 8=absolute-VA/4=RVA), largest first. When no strong plain table exists it hints at recover_cfg — a control-flow-flattened / MBA VM computes its successors per block (jmp rax) and has no pointer table to find.",
             inputSchema={"type": "object", "properties": {
                 "path": {"type": "string", "description": "Path to the PE file."},
             }, "required": ["path"]}),
        Tool(name="recover_cfg",
             description="Recover the real control-flow graph of a control-flow-flattened / MBA-obfuscated x86-64 function whose blocks end in a computed `jmp rax` (a common VM-obfuscation pattern). For each block it liveness-backtracks to the 'footer expression' that computes the jump target, then emulates that footer with the whole image mapped (so its data-blob reads resolve) to read the successor — resolving conditional footers (SETZ/SETNZ/SETGE) to both edges. Returns blocks, edges, an unresolved count, and a Graphviz DOT — the edges a linear disassembler cannot see. Needs capstone + the 'emulate' extra (unicorn, pefile).",
             inputSchema={"type": "object", "properties": {
                 "path": {"type": "string", "description": "Path to the PE file."},
                 "entry": {"type": "string", "description": "Function entry address (e.g. 0x1400202b0)."},
                 "max_blocks": {"type": "integer", "default": 4000},
             }, "required": ["path", "entry"]}),
        Tool(name="recover_cmp_string",
             description="Reconstruct a hidden string from a chain of BYTE COMPARISONS in a function — the expected password / serial / key-sequence when a check is compiled as an unrolled cascade `if(buf[0]=='L') if(buf[1]=='L') if(buf[2]=='U')...`. Such a string exists ONLY as the immediate operands of `cmp` instructions and never appears contiguously, so get_strings and deobfuscate_strings (FLOSS: stack-built / decoded strings) both miss it. Arch-aware (handles 32-bit targets, unlike the x64-only model disasm): it disassembles from the function VA, collects printable-ASCII cmp-immediates in address order (reading the last operand, so a memory displacement is never mistaken for a value, and non-printable length checks like `cmp eax,0xf` are filtered), and groups them into candidate strings ranked by length (e.g. a movement sequence like \"LLURULDUL\"). Needs capstone ('disasm' extra).",
             inputSchema={"type": "object", "properties": {
                 "path": {"type": "string", "description": "Binary to analyze (PE/ELF/Mach-O)."},
                 "address": {"type": "string", "description": "Function VA to scan (hex, e.g. 0x004024e0)."},
                 "max_bytes": {"type": "integer", "default": 2048, "description": "Bytes of code to disassemble from the VA."},
                 "min_run": {"type": "integer", "default": 4, "description": "Minimum characters for a reported candidate."},
                 "gap": {"type": "integer", "default": 128, "description": "Max byte gap between consecutive compares before a new candidate starts."},
             }, "required": ["path", "address"]}),
        Tool(name="recover_data_bytes",
             description="Reassemble a hardcoded byte array a compiler built with INLINE IMMEDIATE STORES (`mov byte/word/dword ptr [buf+i], imm`) instead of a contiguous .data blob — an embedded key, blob, shellcode or lookup table that get_strings and deobfuscate_strings (FLOSS) miss because it is mixed/non-printable and never contiguous. Disassembles from the function VA (arch-aware, 32-bit included), collects immediate stores to memory in program order, and splits word/dword/qword immediates into little-endian bytes. Optional gadget_target inverts an ADDITIVE gadget: when the target computes and executes `data[i] + input[i]` per byte, the input making every byte == gadget_target is `(gadget_target - data[i]) & 0xff` — pass 0xC3 for a `ret`. Returns the byte array (hex), the per-store list, and any derived input. Needs capstone ('disasm' extra).",
             inputSchema={"type": "object", "properties": {
                 "path": {"type": "string", "description": "Binary to analyze (PE/ELF/Mach-O)."},
                 "address": {"type": "string", "description": "Function VA whose inline stores build the array (hex)."},
                 "max_bytes": {"type": "integer", "default": 4096, "description": "Bytes of code to disassemble from the VA."},
                 "max_stores": {"type": "integer", "default": 512, "description": "Stop after this many immediate stores."},
                 "gadget_target": {"type": "string", "description": "Invert an additive gadget: return (target - data[i]) & 0xff, e.g. \"0xC3\" for ret."},
             }, "required": ["path", "address"]}),
        Tool(name="decrypt_blob",
             description="Decrypt a captured / embedded blob with a KNOWN key using a common symmetric cipher — RC4, XOR (single or multi-byte), or the ChaCha20 / Salsa20 stream ciphers. The reusable last step of a network-capture or file-encryptor RE challenge once the key is recovered, and for malware config/traffic decryption; chimera otherwise only FOUND AES keys (find_aes_keys) and hid an RC4 inside the PDF decryptor. ChaCha20/Salsa20 (recognisable by the \"expand 32-byte k\" constant) take a `nonce` (ChaCha20: 8 or 12 bytes, 12 = RFC 7539; Salsa20: 8 bytes) and an optional initial block `counter` (the `in[12]` state word). Decodes the ciphertext + nonce from raw/hex/base64 and the key from raw/hex/utf16le (utf16le = a hex-DIGEST string as UTF-16LE). Returns the plaintext hex, a printable preview, and best-effort UTF-8 / UTF-16LE text (Windows malware often keeps wide-char plaintext). Recovering the key itself (an RNG-seed brute-force, a KDF, or an RSA decrypt — see rsa_recover) is target-specific and not done here.",
             inputSchema={"type": "object", "properties": {
                 "data": {"type": "string", "description": "Ciphertext (encoding set by in_encoding)."},
                 "key": {"type": "string", "description": "Key (encoding set by key_encoding)."},
                 "algo": {"type": "string", "enum": ["rc4", "xor", "chacha20", "salsa20"], "default": "rc4", "description": "Cipher."},
                 "in_encoding": {"type": "string", "enum": ["raw", "hex", "base64"], "default": "raw", "description": "How `data` is encoded."},
                 "key_encoding": {"type": "string", "enum": ["raw", "hex", "utf16le"], "default": "raw", "description": "How `key` is encoded (utf16le = a hex-digest string as UTF-16LE)."},
                 "nonce": {"type": "string", "description": "Nonce for chacha20/salsa20 (decoded per nonce_encoding)."},
                 "nonce_encoding": {"type": "string", "enum": ["raw", "hex", "base64"], "default": "hex", "description": "How `nonce` is encoded."},
                 "counter": {"type": "integer", "default": 0, "description": "Initial ChaCha20 block counter (in[12] state word)."},
             }, "required": ["data", "key"]}),
        Tool(name="crypto_triage",
             description="Detect keystream REUSE across several ciphertexts (the multi-time-pad weakness) and crib-drag to recover plaintext — NO key needed. A stream cipher (RC4/ChaCha/AES-CTR/hand-rolled XOR) is broken the moment the same key+nonce encrypts two messages: C_i⊕C_j = P_i⊕P_j. This scores the reuse signal (shared ciphertext prefixes, zero-XOR runs, printable-XOR fraction — random independent streams XOR to ~31% printable and share no prefix) across ≥2 blobs and, given a `crib` (a guessed plaintext fragment), slides it to recover the other plaintexts at matched offsets (the classic two-time-pad attack). FLARE-On 13 ch5 'catthief' re-keyed RC4 per message → all exfil bodies shared one keystream; this flags it. Complements decrypt_blob (which applies a KNOWN key). Returns pairwise stats, a verdict, and crib hits.",
             inputSchema={"type": "object", "properties": {
                 "ciphertexts": {"type": "array", "items": {"type": "string"}, "description": "≥2 ciphertext blobs (encoding set by enc)."},
                 "enc": {"type": "string", "enum": ["hex", "base64", "file", "raw"], "default": "hex", "description": "How each ciphertext is given (file = a path)."},
                 "crib": {"type": "string", "description": "Optional known/guessed plaintext fragment to drag (recovers other plaintexts where it matches)."},
             }, "required": ["ciphertexts"]}),
        Tool(name="rsa_recover",
             description="Recover an RSA plaintext from the material an encryptor leaves behind — a modulus N, ciphertext c, and public exponent e (default 0x10001), optionally a private exponent d or the primes p,q. With d (or p,q → derive d) it decrypts m = c^d mod N. With only N/e/c it computes m = c^e mod N, which returns the plaintext when the encryptor 'encrypted' with the PRIVATE exponent — a classic bug where the modinv is written back over the public exponent, so the stored value is m^d and raising it to e recovers m with no private key — and otherwise verifies a signature. `factor=true` tries Fermat factorization of N (only works when the primes are close). Returns m as int/hex and as big- AND little-endian bytes with text previews (mind the endianness — a recovered symmetric key is often little-endian; feed it to decrypt_blob). Focused: modpow + Fermat only, no Wiener/common-modulus/factordb (use RsaCtfTool for those). No network.",
             inputSchema={"type": "object", "properties": {
                 "n": {"type": "string", "description": "Modulus N (hex by default; see base)."},
                 "c": {"type": "string", "description": "Ciphertext c."},
                 "e": {"type": "string", "description": "Public exponent e (default 0x10001)."},
                 "d": {"type": "string", "description": "Private exponent d, if known."},
                 "p": {"type": "string", "description": "Prime p, if known."},
                 "q": {"type": "string", "description": "Prime q, if known."},
                 "base": {"type": "string", "enum": ["hex", "dec", "b64"], "default": "hex", "description": "How bare (no-0x) numeric inputs are read."},
                 "factor": {"type": "boolean", "default": False, "description": "Attempt Fermat factorization of N (close primes)."},
             }, "required": ["n", "c"]}),
        Tool(name="symexec",
             description="Symbolic execution (angr): find the INPUT that drives the binary to a target — a win address (`find`) or a state whose stdout contains a string (`find_stdout`), while avoiding failure addresses/strings. Declare the symbolic input as `stdin_len` bytes of stdin and/or `sym_argv` (byte-lengths of symbolic argv entries). Returns the concrete stdin/argv that reaches it. Use for crackme/keygen/serial checks where pathfind (needs a recovered FSM) and emulate_function (runs one chosen path) can't discover an unknown input. Needs angr (pip install angr); bounded by timeout + state cap.",
             inputSchema={"type": "object", "properties": {
                 "path": {"type": "string", "description": "Binary to solve (defaults to the loaded analysis)."},
                 "find": {"type": "string", "description": "Win address (hex, e.g. 0x401337)."},
                 "find_stdout": {"type": "string", "description": "String the winning state must have printed (alternative to find)."},
                 "avoid": {"type": "array", "items": {"type": "string"}, "description": "Failure addresses to prune (hex)."},
                 "avoid_stdout": {"type": "string", "description": "String a failing state prints (e.g. 'Wrong')."},
                 "stdin_len": {"type": "integer", "description": "Symbolic stdin length in bytes."},
                 "sym_argv": {"type": "array", "items": {"type": "integer"}, "description": "Byte-lengths of symbolic argv entries after argv[0]."},
                 "timeout": {"type": "integer", "default": 120},
             }, "required": []}),
        Tool(name="decompile",
             description="Decompile ONE native function to C at a given address, on demand (no prior analyze needed — pass path=). Prefers r2ghidra's `pdg` (the real Ghidra decompiler, genuine C) and falls back to radare2's built-in `pdc` when r2ghidra isn't installed; `decompiler` can force pdg, pdc, ida, or ghidra. `ida` uses IDA Pro's Hex-Rays (needs IDA + IDA_PATH); `ghidra` drives a STANDALONE Ghidra headless (needs GHIDRA_HOME) — the fallback when r2ghidra won't build, giving genuine Ghidra C (it imports + analyzes the whole binary, so it's the HEAVY option). Does a targeted `af` (not a full analysis) for pdg/pdc so they're fast on large binaries. For a whole loaded project's functions use get_function instead. Returns the C code + which backend produced it.",
             inputSchema={"type": "object", "properties": {
                 "address": {"type": "string", "description": "Function address (e.g. 0x401000)."},
                 "path": {"type": "string", "description": "Binary to decompile (defaults to the loaded analysis)."},
                 "decompiler": {"type": "string", "enum": ["pdg", "pdc", "ida", "ghidra"],
                                "description": "Force a backend (default: pdg then pdc; 'ida' = Hex-Rays; 'ghidra' = standalone Ghidra headless, needs GHIDRA_HOME)."},
             }, "required": ["address"]}),
        Tool(name="core_triage",
             description="Triage an ELF process CORE DUMP (a crashed userspace process), the gap Volatility (`memory`, whole-OS images) doesn't cover. Parses PT_LOAD ranges, the NT_FILE module mappings and the NT_PRSTATUS registers per thread; shows the crashing thread's registers and which module the faulting `rip` and the stack return address fall in (crash→module correlation), and lets you resolve any address to module+offset (resolve_addr), search process memory for bytes (search_hex), or dump a region (dump). This is the backbone of a backdoored-library post-mortem — correlate the crash to the implicated module, then find the attacker payload resident in memory (pair with find_aes_keys over a dumped region). x86-64 decodes registers; other arches still get maps + read/search.",
             inputSchema={"type": "object", "properties": {
                 "path": {"type": "string", "description": "Path to the ELF core dump."},
                 "resolve_addr": {"type": "string", "description": "Resolve this virtual address (hex) to module+offset."},
                 "search_hex": {"type": "string", "description": "Find these hex bytes across mapped memory."},
                 "dump": {"type": "object", "properties": {
                     "address": {"type": "string"}, "length": {"type": "integer"}},
                     "description": "Dump memory at {address, length}."},
             }, "required": ["path"]}),
        Tool(name="patch",
             description="Apply in-place byte or assembly patches to a PE / ELF / Mach-O binary and write a patched copy — NOP an anti-debug check, force a conditional jump, stub an import, or drop in new code. Each patch is `nop:true` (overwrite the instruction(s) at the VA with NOPs, auto-sized by disassembly so short AND near jumps both work — the 'just NOP the check' patch, no byte-counting), or raw `bytes_hex`, or `asm` source (assembled at its VA via keystone, so relative jmp/call/branch offsets are correct); `arch` defaults to the binary's own machine (x86_64/x86/arm64/arm/thumb). Also applies bundled `recipes` by name (see `chimera patch --list-recipes`). Defaults to dry_run=true — returns the before/after diff without writing; set dry_run=false (and optionally out=) to save. `nop` needs the 'disasm' extra (capstone); `asm` needs the 'patch' extra (keystone).",
             inputSchema={"type": "object", "properties": {
                 "path": {"type": "string", "description": "Binary to patch (defaults to the loaded analysis)."},
                 "patches": {"type": "array", "description": "Patches to apply.", "items": {"type": "object", "properties": {
                     "address": {"type": "string", "description": "Virtual address (hex, e.g. 0x140001234)."},
                     "nop": {"type": "boolean", "description": "NOP the instruction(s) at the VA, auto-sized by disassembly (no byte-counting). Pair with 'count'."},
                     "count": {"type": "integer", "default": 1, "description": "Instructions to NOP when nop:true (default 1)."},
                     "asm": {"type": "string", "description": "Assembly source to encode at the VA, e.g. 'xor eax,eax; ret'."},
                     "bytes_hex": {"type": "string", "description": "Raw bytes as hex (alternative to asm)."},
                     "arch": {"type": "string", "description": "Arch for asm (default: auto from the binary)."},
                     "description": {"type": "string"},
                 }}},
                 "recipes": {"type": "array", "items": {"type": "string"}, "description": "Bundled recipe names to apply."},
                 "out": {"type": "string", "description": "Output path (default: <binary>.patched.<ext>)."},
                 "dry_run": {"type": "boolean", "default": True, "description": "Preview the diff without writing (default true)."},
             }, "required": []}),
        Tool(name="yara_solve",
             description="SOLVE a YARA rule — synthesise a file that MATCHES its condition, the inverse of yara_scan. Translates the condition (byte/int reads uint8/uint16/uint32/int* incl. be variants, filesize, C-arithmetic and comparisons, joined by `and`) to a Z3 bit-vector model over the file bytes, and brute-forces short hash.md5/sha1/sha256/crc32(offset,len) windows to pin their exact bytes. This is the YARA-keygen CTF solver (reverse a rule to the flag it accepts) and a defensive rule-QA check (does any input satisfy this, and what does it look like?). Pass the rule as `source` or `path`; `size` supplies the length when there is no `filesize == N`; verifies the result with yara-python. Needs the 'solve' extra (z3). Unsupported atoms (or/not/for..of/string-identifiers) are reported, not silently dropped.",
             inputSchema={"type": "object", "properties": {
                 "source": {"type": "string", "description": "The YARA rule text (alternative to path)."},
                 "path": {"type": "string", "description": "Path to a .yara/.yar file (alternative to source)."},
                 "size": {"type": "integer", "description": "File length in bytes, when the rule has no `filesize == N`."},
                 "max_hash_len": {"type": "integer", "default": 3, "description": "Max window length to brute-force for hash.* atoms."},
                 "binary": {"type": "boolean", "default": False, "description": "Allow non-printable bytes (default assumes an ASCII flag)."},
             }, "required": []}),
        Tool(name="find_aes_keys",
             description="Recover AES-128/192/256 keys by locating their expanded key schedule in bytes — a file (memory dump / core / any blob), a live process's memory (via /proc, writable regions), or a hex string. The schedule satisfies the AES KeyExpansion recurrence, so it is self-checking: a key computed at RUNTIME behind obfuscation (derived/decrypted/unpacked, never a literal in the binary) is still recoverable once resident. Reports each key (hex), its bit size, address/offset, and the 16 bytes after the schedule as a candidate IV (tiny-AES-c layout). Pair with a process dump or a frozen target (dynamic-analysis skill).",
             inputSchema={"type": "object", "properties": {
                 "file": {"type": "string", "description": "Path to a file/dump to scan."},
                 "pid": {"type": "integer", "description": "PID of a live process to scan (/proc)."},
                 "hex": {"type": "string", "description": "A hex byte string to scan directly."},
             }}),
        Tool(name="pathfind",
             description="Shortest labelled path through a graph/FSM edge list from a start node to an accepting node — the reusable core of 'find the input that drives this state machine to accept' (e.g. recover a password from a disassembled validator). Edges map a node to [label, next_node] transitions; the concatenated edge labels ARE the accepting input. Pure BFS, no binary needed. Use exact_length to require a path of exactly N edges (the 'N-char password' shape where shorter accepts must be rejected).",
             inputSchema={"type": "object", "properties": {
                 "edges": {"type": "object", "description": "Map of node -> list of [label, next_node] pairs."},
                 "start": {"description": "The start node."},
                 "accept": {"description": "An accepting node, or a list of accepting nodes."},
                 "exact_length": {"type": "integer", "description": "Require exactly this many edges."},
                 "max_depth": {"type": "integer", "description": "Bound the search to this many edges."},
             }, "required": ["edges", "start", "accept"]}),
        Tool(name="eth_fetch",
             description="Read LIVE EVM on-chain state over JSON-RPC — the complement to evm_tour (which is offline bytecode only). Two read-only ops: an `eth_call` (ABI-encode a method call to a contract and decode the result) or `get_transaction` (recover a tx's calldata). This is the exact capability for triaging an EtherHiding / ClearFake dropper, which hides its real payload in a contract's return value or in a storage-write transaction's calldata and pulls it at runtime. Pass tx_hash for get_transaction, or to+method_id (+param_types/args/return_type/block) for eth_call. NETWORK IS OFF unless allow_network=true is passed explicitly — nothing touches the network otherwise. Minimal ABI codec (string/address/bytes/uintN).",
             inputSchema={"type": "object", "properties": {
                 "rpc": {"type": "string", "description": "JSON-RPC endpoint URL."},
                 "allow_network": {"type": "boolean", "default": False, "description": "Required to make the live read-only request."},
                 "tx_hash": {"type": "string", "description": "get_transaction mode: recover this tx's calldata."},
                 "to": {"type": "string", "description": "eth_call mode: contract address."},
                 "method_id": {"type": "string", "description": "eth_call mode: 4-byte selector (0x…)."},
                 "param_types": {"type": "array", "items": {"type": "string"}, "description": "ABI types of the call args."},
                 "args": {"type": "array", "items": {"type": "string"}, "description": "Call arg values (paired with param_types)."},
                 "block": {"type": "string", "description": "Block tag/number (default latest)."},
                 "return_type": {"type": "string", "description": "ABI type to decode the result as (e.g. string)."},
             }, "required": ["rpc"]}),
        Tool(name="evm_tour",
             description="Statically triage EVM smart-contract bytecode (as a hex string or a path to a hex/binary file) WITHOUT an Ethereum node: split a constructor (deploy) blob to its runtime, strip the solc metadata trailer, recover the dispatcher's 4-byte function selectors, and disassemble. Optionally pass calldata (selector||abi-encoded args) to EXECUTE a leaf pure/view function through a bounded stack-machine interpreter and get the returned bytes — verify an on-chain formula by execution instead of deploying to a testnet. The interpreter models stack/memory/calldata only (no storage, external calls, gas or logs); such an opcode errors rather than returning a wrong answer.",
             inputSchema={"type": "object", "properties": {
                 "source": {"type": "string", "description": "EVM bytecode as a hex string (0x-optional), or a path to a file containing hex or raw bytecode."},
                 "calldata": {"type": "string",
                              "description": "Optional hex calldata (selector||abi-args). When given, runs the runtime as a pure function and returns the output bytes instead of the tour."},
             }, "required": ["source"]}),
        Tool(name="pdf_tour",
             description="Statically triage a PDF: recover objects even with no xref/EOF (which strict parsers refuse), flag parser-differential traps (duplicate /Root, name-hex-obfuscated keys like /#52#6F#6F#74, duplicate/commented objects, missing xref/EOF), and — when the file uses the Standard security handler (R2-R6, RC4/AESV2/AESV3) — derive the key from the empty or supplied password, decrypt the streams, and list/dump any hidden inline images. Read-only; never renders or executes the document. Use for suspicious/malformed/encrypted PDFs.",
             inputSchema={"type": "object", "properties": {
                 "path": {"type": "string", "description": "Path to the PDF file."},
                 "password": {"type": "string", "default": "",
                              "description": "User/owner password to try (default: empty)."},
                 "extract_images_dir": {"type": "string",
                              "description": "Directory to write any inline images to."},
             }, "required": ["path"]}),
        Tool(name="pcap_extract",
             description="Extract application-layer payloads from a packet capture (.pcap/.pcapng) via tshark — for the malware+capture class (reconstruct what was exfiltrated / C2'd). `action`: `http` (default) returns every HTTP request/response + their reconstructed (de-chunked, de-gzipped) bodies — FLARE-On 13 ch5 'catthief' POSTed the stolen files as HTTP bodies; `follow` + `stream` dumps a raw TCP stream (direction both|c2s|s2c); `conversations` lists the TCP conversation table. Bodies return as hex (or saved to `out_dir`). Needs tshark (`apt install tshark`).",
             inputSchema={"type": "object", "properties": {
                 "path": {"type": "string", "description": "Capture file (.pcap/.pcapng)."},
                 "action": {"type": "string", "enum": ["http", "follow", "conversations"], "default": "http"},
                 "stream": {"type": "integer", "description": "tcp.stream index (for action=follow)."},
                 "direction": {"type": "string", "enum": ["both", "c2s", "s2c"], "default": "both"},
                 "out_dir": {"type": "string", "description": "Save HTTP bodies here instead of returning hex."},
             }, "required": ["path"]}),
        Tool(name="wasm_decompile",
             description="Decompile a WebAssembly (.wasm) module to a readable C-like form — chimera otherwise has no WASM path (analyze used to mis-sniff the `\\0asm` magic as ELF and abort). Ships the recipe that actually works on a STRIPPED / Go-compiled module: a binaryen round-trip (`wasm-opt -all` re-serialises the module, which is what un-breaks wabt's wasm-decompile; Go 1.24+ wasm needs the `-all` flag) then `wasm-decompile`. Also emits the `.wat` text disassembly when `wat` is set. The output is large (a 6 MB Go module decompiles to ~780k lines), so it is written to disk — the tool returns the file paths, the line count, and a head preview; grep/read the file for the rest. Pair with `analyze` (section/import/export + Go-WASM recon) and `wasm_oracle` (run it). Needs wabt + binaryen (apt install wabt binaryen, or set $CHIMERA_WASM_TOOLS).",
             inputSchema={"type": "object", "properties": {
                 "path": {"type": "string", "description": "Path to the .wasm module."},
                 "out_dir": {"type": "string", "description": "Output directory (default: <name>_wasm beside the input)."},
                 "wat": {"type": "boolean", "default": False,
                         "description": "Also emit the full .wat text disassembly (wasm2wat)."},
             }, "required": ["path"]}),
        Tool(name="wasm_oracle",
             description="Run a WebAssembly module headless under Node and call one of its functions with your inputs — the dynamic lever for a Go-WASM target (a Chrome-extension verifier, a crackme) whose real entry point is published at runtime via `js.Global().Set(\"check\", …)` and so is NOT a wasm export and can't be reached statically. Reusing the Go runtime glue (`wasm_exec.js`, auto-located beside the module), it instantiates with `go.importObject`, runs `go.run(instance)` WITHOUT awaiting (Go's main blocks to keep the JS callbacks alive), then calls `export(input)` for each input and captures the return — the black-box oracle an all-or-nothing validator needs. Set `trace=true` to instead build an instrumented copy (binaryen `--log-execution`) and return, per input, the exact function subtree that executed (function indices, highest-first — Go compiles the main package last, so the real check routine is near the top): the \"which functions did input X hit\" lever that locates the check among thousands of anonymous funcs. Needs node (+ wabt/binaryen for trace). Confined: the module only reads its own files.",
             inputSchema={"type": "object", "properties": {
                 "path": {"type": "string", "description": "Path to the .wasm module."},
                 "inputs": {"type": "array", "items": {"type": "string"},
                            "description": "Input string(s) to pass to the exported function."},
                 "export": {"type": "string", "default": "check",
                            "description": "Name of the js.Global().Set-exported function to call."},
                 "trace": {"type": "boolean", "default": False,
                           "description": "Instrument with --log-execution and return the executed function subtree per input."},
                 "go": {"type": "boolean",
                        "description": "Force Go-WASM mode (default: auto-detect via a sibling wasm_exec.js)."},
                 "wasm_exec": {"type": "string",
                               "description": "Path to wasm_exec.js (default: sibling of the module)."},
             }, "required": ["path", "inputs"]}),
    ]
