"""Populate the unified model from ILSpy-decompiled C#.

ilspycmd emits one `.cs` file per assembly by default, so the pipeline
previously recorded a single model entry — the *file* — and the classes,
methods and string literals inside it never reached the model at all. On
a managed binary that is nearly everything there is: the native stub a PE
pipeline can see is a few hundred bytes of loader.

Parsing is deliberately regex-level rather than a real C# grammar. The
input is machine-generated by one decompiler with a stable layout, and
the goal is an index an analyst can search — not a compiler front end.
"""

from __future__ import annotations

import logging
import re
from pathlib import Path

from chimera.model.function import FunctionInfo
from chimera.model.program import UnifiedProgramModel

logger = logging.getLogger(__name__)

_TYPE_RE = re.compile(
    r"^\s*(?:\[[^\]]*\]\s*)*"
    r"(?:public|internal|private|protected)?\s*"
    r"(?:static\s+|sealed\s+|abstract\s+|partial\s+)*"
    r"(class|struct|interface|enum)\s+"
    r"([A-Za-z_<>][\w<>.`]*)",
    re.MULTILINE,
)

# A method line: modifiers, return type, name, parenthesised parameters,
# not terminated by `;` (which would make it an abstract/extern declaration
# with no body) and not a control-flow keyword.
_METHOD_RE = re.compile(
    r"^[ \t]+(?:\[[^\]]*\]\s*)*"
    r"((?:public|internal|private|protected|static|virtual|override|sealed|"
    r"extern|unsafe|async)\s+)+"
    r"([\w<>\[\],.`?]+)\s+"
    r"([A-Za-z_<][\w<>`]*)\s*"
    r"\(([^)]*)\)",
    re.MULTILINE,
)

_NAMESPACE_RE = re.compile(r"^namespace\s+([\w.]+)", re.MULTILINE)

# C# string literal, honouring escapes. Verbatim (@"...") strings are not
# matched: they are rare in decompiler output and would need separate
# handling for doubled quotes.
_STRING_RE = re.compile(r'"((?:\\.|[^"\\])*)"')

_KEYWORDS = frozenset({
    "if", "for", "foreach", "while", "switch", "catch", "using", "lock",
    "return", "new", "do", "else", "fixed", "sizeof", "typeof", "nameof",
})


def _iter_sources(sources_dir: Path):
    root = Path(sources_dir)
    if root.is_file():
        yield root
        return
    if not root.exists():
        return
    yield from sorted(root.rglob("*.cs"))


def _types_from_text(model, text, source_label, added, max_types):
    ns_match = _NAMESPACE_RE.search(text)
    namespace = ns_match.group(1) if ns_match else ""
    for kind, name in _TYPE_RE.findall(text):
        if added >= max_types:
            break
        fqcn = f"{namespace}.{name}" if namespace else name
        model.add_function(FunctionInfo(
            address=f"dotnet:{fqcn}",
            name=name,
            original_name=fqcn,
            language="csharp",
            classification="unknown",
            layer="dotnet",
            source_backend="ilspy",
            metadata={"kind": kind, "namespace": namespace,
                      "file": source_label},
        ))
        added += 1
    return added


def ingest_ilspy_types(
    model: UnifiedProgramModel,
    sources_dir: Path,
    *,
    max_types: int = 10000,
) -> int:
    """Add one FunctionInfo per declared type. Returns the count added."""
    added = 0
    for path in _iter_sources(sources_dir):
        try:
            text = path.read_text(errors="replace")
        except OSError:
            continue
        added = _types_from_text(model, text, str(path), added, max_types)
    return added


def ingest_ilspy_methods(
    model: UnifiedProgramModel,
    sources_dir: Path,
    *,
    max_methods: int = 50000,
) -> int:
    """Add one FunctionInfo per method body. Returns the count added."""
    added = 0
    for path in _iter_sources(sources_dir):
        try:
            text = path.read_text(errors="replace")
        except OSError:
            continue
        added = _methods_from_text(model, text, str(path), added, max_methods)
    return added


def _methods_from_text(model, text, source_label, added, max_methods):
    ns_match = _NAMESPACE_RE.search(text)
    namespace = ns_match.group(1) if ns_match else ""
    for match in _METHOD_RE.finditer(text):
        if added >= max_methods:
            break
        _mods, ret, name, params = match.groups()
        if name in _KEYWORDS or ret in _KEYWORDS:
            continue
        line = text.count("\n", 0, match.start()) + 1
        model.add_function(FunctionInfo(
            address=f"dotnet:{namespace}::{name}@{line}" if namespace
                    else f"dotnet:{name}@{line}",
            name=name,
            original_name=f"{namespace}.{name}" if namespace else name,
            language="csharp",
            classification="unknown",
            layer="dotnet",
            source_backend="ilspy",
            metadata={"returns": ret, "params": params.strip(),
                      "file": source_label, "line": line},
        ))
        added += 1
    return added


def ingest_ilspy_strings(
    model: UnifiedProgramModel,
    sources_dir: Path,
    *,
    max_strings: int = 5000,
    min_len: int = 4,
    max_len: int = 512,
) -> int:
    """Add string literals found in decompiled C#. Returns the count added.

    On a managed binary these are the strings that matter — a PE string
    scrape only reaches the native stub and the resource directory.
    """
    added = 0
    seen: set[str] = set()
    for path in _iter_sources(sources_dir):
        try:
            text = path.read_text(errors="replace")
        except OSError:
            continue
        added = _strings_from_text(model, text, path.name, added, seen,
                                   max_strings, min_len, max_len)
    return added


def _strings_from_text(model, text, source_label, added, seen,
                       max_strings, min_len, max_len):
    for raw in _STRING_RE.findall(text):
        if added >= max_strings:
            return added
        if not (min_len <= len(raw) <= max_len) or raw in seen:
            continue
        seen.add(raw)
        model.add_string(address=f"dotnet:{source_label}", value=raw,
                         section="ilspy")
        added += 1
    return added


def ingest_ilspy_sources(model: UnifiedProgramModel, sources_dir: Path) -> tuple[int, int, int]:
    """Run all three passes. Returns (types, methods, strings) added."""
    types = ingest_ilspy_types(model, sources_dir)
    methods = ingest_ilspy_methods(model, sources_dir)
    strings = ingest_ilspy_strings(model, sources_dir)
    logger.info("ilspy ingest: %d types, %d methods, %d strings",
                types, methods, strings)
    return types, methods, strings


def rehydrate_ilspy_from_cache(model: UnifiedProgramModel, cache,
                               sha256: str) -> tuple[int, int, int]:
    """Replay cached ILSpy output into the model on a warm cache hit.

    The PE pipeline caches the decompiled C# under `ilspy_<name>` with the
    full source inline, so a second analysis re-ingests the managed types,
    methods and strings from the blob — no dependency on the on-disk .cs,
    which may have been cleaned up. Without this a warm cache returns only
    the native functions, which is how an MCP-driven re-analysis dropped a
    .NET binary from 183 functions back to 15.
    """
    types = methods = strings = 0
    seen: set[str] = set()
    for key in cache.list_keys(sha256):
        if not key.startswith("ilspy_"):
            continue
        blob = cache.get_json(sha256, key)
        if not isinstance(blob, dict):
            continue
        for entry in blob.get("types", []) or []:
            text = entry.get("decompiled")
            if not text:
                continue
            label = entry.get("file", key)
            types = _types_from_text(model, text, label, types, 10000)
            methods = _methods_from_text(model, text, label, methods, 50000)
            strings = _strings_from_text(model, text, label, strings, seen,
                                         5000, 4, 512)
    if types or methods or strings:
        logger.info("ilspy rehydrate: %d types, %d methods, %d strings",
                    types, methods, strings)
    return types, methods, strings
