"""Populate the unified model from ILSpy-decompiled C#.

ilspycmd emits one `.cs` file per assembly by default, so the pipeline
previously recorded a single model entry — the *file* — and the classes,
methods and string literals inside it never reached the model at all. On
a managed binary that is nearly everything there is: the native stub a PE
pipeline can see is a few hundred bytes of loader.

Parsing is deliberately regex-level rather than a real C# grammar. The
input is machine-generated by one decompiler with a stable layout, and
the goal is an index an analyst can search — not a compiler front end.
"""

from __future__ import annotations

import logging
import re
from pathlib import Path

from chimera.model.function import FunctionInfo
from chimera.model.program import UnifiedProgramModel

logger = logging.getLogger(__name__)

_TYPE_RE = re.compile(
    r"^\s*(?:\[[^\]]*\]\s*)*"
    r"(?:public|internal|private|protected)?\s*"
    r"(?:static\s+|sealed\s+|abstract\s+|partial\s+)*"
    r"(class|struct|interface|enum)\s+"
    r"([A-Za-z_<>][\w<>.`]*)",
    re.MULTILINE,
)

# A method line: modifiers, return type, name, parenthesised parameters,
# not terminated by `;` (which would make it an abstract/extern declaration
# with no body) and not a control-flow keyword.
_METHOD_RE = re.compile(
    r"^[ \t]+(?:\[[^\]]*\]\s*)*"
    r"((?:public|internal|private|protected|static|virtual|override|sealed|"
    r"extern|unsafe|async)\s+)+"
    r"([\w<>\[\],.`?]+)\s+"
    r"([A-Za-z_<][\w<>`]*)\s*"
    r"\(([^)]*)\)",
    re.MULTILINE,
)

_NAMESPACE_RE = re.compile(r"^namespace\s+([\w.]+)", re.MULTILINE)

# C# string literal, honouring escapes. Verbatim (@"...") strings are not
# matched: they are rare in decompiler output and would need separate
# handling for doubled quotes.
_STRING_RE = re.compile(r'"((?:\\.|[^"\\])*)"')

_KEYWORDS = frozenset({
    "if", "for", "foreach", "while", "switch", "catch", "using", "lock",
    "return", "new", "do", "else", "fixed", "sizeof", "typeof", "nameof",
})


def _iter_sources(sources_dir: Path):
    root = Path(sources_dir)
    if root.is_file():
        yield root
        return
    if not root.exists():
        return
    yield from sorted(root.rglob("*.cs"))


def ingest_ilspy_types(
    model: UnifiedProgramModel,
    sources_dir: Path,
    *,
    max_types: int = 10000,
) -> int:
    """Add one FunctionInfo per declared type. Returns the count added."""
    added = 0
    for path in _iter_sources(sources_dir):
        try:
            text = path.read_text(errors="replace")
        except OSError:
            continue
        namespace = (_NAMESPACE_RE.search(text) or [None, ""])[1] if _NAMESPACE_RE.search(text) else ""
        for kind, name in _TYPE_RE.findall(text):
            if added >= max_types:
                break
            fqcn = f"{namespace}.{name}" if namespace else name
            model.add_function(FunctionInfo(
                address=f"dotnet:{fqcn}",
                name=name,
                original_name=fqcn,
                language="csharp",
                classification="unknown",
                layer="dotnet",
                source_backend="ilspy",
                metadata={"kind": kind, "namespace": namespace,
                          "file": str(path)},
            ))
            added += 1
    return added


def ingest_ilspy_methods(
    model: UnifiedProgramModel,
    sources_dir: Path,
    *,
    max_methods: int = 50000,
) -> int:
    """Add one FunctionInfo per method body. Returns the count added."""
    added = 0
    for path in _iter_sources(sources_dir):
        try:
            text = path.read_text(errors="replace")
        except OSError:
            continue
        ns_match = _NAMESPACE_RE.search(text)
        namespace = ns_match.group(1) if ns_match else ""
        for match in _METHOD_RE.finditer(text):
            if added >= max_methods:
                break
            _mods, ret, name, params = match.groups()
            if name in _KEYWORDS or ret in _KEYWORDS:
                continue
            line = text.count("\n", 0, match.start()) + 1
            model.add_function(FunctionInfo(
                address=f"dotnet:{namespace}::{name}@{line}" if namespace
                        else f"dotnet:{name}@{line}",
                name=name,
                original_name=f"{namespace}.{name}" if namespace else name,
                language="csharp",
                classification="unknown",
                layer="dotnet",
                source_backend="ilspy",
                metadata={"returns": ret, "params": params.strip(),
                          "file": str(path), "line": line},
            ))
            added += 1
    return added


def ingest_ilspy_strings(
    model: UnifiedProgramModel,
    sources_dir: Path,
    *,
    max_strings: int = 5000,
    min_len: int = 4,
    max_len: int = 512,
) -> int:
    """Add string literals found in decompiled C#. Returns the count added.

    On a managed binary these are the strings that matter — a PE string
    scrape only reaches the native stub and the resource directory.
    """
    added = 0
    seen: set[str] = set()
    for path in _iter_sources(sources_dir):
        try:
            text = path.read_text(errors="replace")
        except OSError:
            continue
        for raw in _STRING_RE.findall(text):
            if added >= max_strings:
                return added
            if not (min_len <= len(raw) <= max_len) or raw in seen:
                continue
            seen.add(raw)
            model.add_string(address=f"dotnet:{path.name}", value=raw,
                             section="ilspy")
            added += 1
    return added


def ingest_ilspy_sources(model: UnifiedProgramModel, sources_dir: Path) -> tuple[int, int, int]:
    """Run all three passes. Returns (types, methods, strings) added."""
    types = ingest_ilspy_types(model, sources_dir)
    methods = ingest_ilspy_methods(model, sources_dir)
    strings = ingest_ilspy_strings(model, sources_dir)
    logger.info("ilspy ingest: %d types, %d methods, %d strings",
                types, methods, strings)
    return types, methods, strings
