"""chimera.cli — gdb export cmd commands."""

from __future__ import annotations

import asyncio
import logging
from pathlib import Path

import click

from chimera.cli._root import main

logger = logging.getLogger(__name__)



# ----------------------------------------------------------------------
# gdb-export — emit a .gdbinit with one $name -> address for each function
# ----------------------------------------------------------------------


@main.command("gdb-export")
@click.argument("path", type=click.Path(exists=True, dir_okay=False))
@click.option("--cache-dir", type=click.Path(), default=None)
@click.option("--project-dir", type=click.Path(), default=None)
@click.option("--out", "out_path", type=click.Path(), default=None,
              help="Output path (default: <binary>.gdbinit)")
def gdb_export(path: str, cache_dir: str | None, project_dir: str | None,
               out_path: str | None):
    """Emit a .gdbinit setting `$function_name` convenience variables.

    Run with:

    \b
      gdb -x app.gdbinit ./app
      (gdb) b *$decode_license
      (gdb) chimera-bp decode_license     # convenience helper

    The init file declares one convenience variable per recovered or
    overlay-renamed function, plus a `chimera-bp` user command that
    accepts function names. Symbols that are not valid gdb identifiers
    are sanitised (dots and slashes become underscores) but kept
    one-to-one so the analyst can recover the mapping.
    """
    asyncio.run(_gdb_export_cmd(path, project_dir, cache_dir, out_path))



async def _gdb_export_cmd(path: str, project_dir: str | None,
                          cache_dir: str | None, out_path: str | None):
    from chimera.core.config import ChimeraConfig
    from chimera.core.engine import ChimeraEngine
    from chimera.core.overlay import ProjectOverlay

    config = ChimeraConfig(
        project_dir=Path(project_dir) if project_dir else Path.cwd() / "chimera_project",
        cache_dir=Path(cache_dir) if cache_dir else Path.cwd() / "chimera_cache",
    )
    engine = ChimeraEngine(config)
    try:
        model = await engine.analyze(path)
        overlay = ProjectOverlay.load(config.project_dir, model.binary.sha256)
        overlay.apply_to_model(model)

        out = Path(out_path) if out_path else Path(path).with_suffix(Path(path).suffix + ".gdbinit")
        emitted = _emit_gdbinit(out, Path(path), model)
        click.echo(f"Wrote {out} ({emitted} symbols)")
    finally:
        await engine.cleanup()



def _emit_gdbinit(out_path: Path, binary: Path, model) -> int:
    """Generate the .gdbinit content. Returns number of symbols emitted."""
    seen: set[str] = set()
    lines: list[str] = [
        "# Generated by chimera gdb-export — function-name → address map.",
        f"# Source binary: {binary}",
        "",
        "set confirm off",
        f"file {binary}",
        "",
    ]
    emitted = 0
    for f in model.functions:
        if not f.address or f.address in {"0xffffffffffffffff", "0x0"}:
            continue
        ident = _sanitise_gdb_var(f.name)
        if not ident or ident in seen:
            continue
        seen.add(ident)
        try:
            int(f.address, 16)
        except ValueError:
            continue
        lines.append(f"set ${ident} = (void *){f.address}")
        emitted += 1

    lines += [
        "",
        "# chimera-bp <name>  — set a breakpoint by recovered name.",
        "define chimera-bp",
        "  if $argc != 1",
        '    printf "usage: chimera-bp <function_name>\\n"',
        "  else",
        "    eval \"break *$arg0\"",
        "  end",
        "end",
        "",
        f"printf \"chimera: {emitted} symbols loaded\\n\"",
    ]
    out_path.write_text("\n".join(lines) + "\n")
    return emitted



def _sanitise_gdb_var(name: str) -> str:
    """Make `name` a valid gdb convenience-variable identifier.

    gdb accepts `[A-Za-z_][A-Za-z0-9_]*`. We strip everything else and
    drop the result if it would start with a digit.
    """
    if not name:
        return ""
    out: list[str] = []
    for ch in name:
        if ch.isalnum() or ch == "_":
            out.append(ch)
        else:
            out.append("_")
    s = "".join(out).strip("_")
    if not s or s[0].isdigit():
        return ""
    return s
